/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 huawei.gltf --transform 
Files: huawei.gltf [8.13MB] > huawei-transformed.glb [543.23KB] (93%)
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/huawei-mate40pro-beff7564c5b149eba067cbb37f325fbc
Title: huawei Mate40pro
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/huawei-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} rotation={[0, Math.PI /1.2, 0]}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="mate03_group1polySurface22_group1_group2_2" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate03_group1polySurface21_3" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate03_polySurface14group1_4" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate03_group1FBXASC229FBXASC177FBXASC143F_b141aae_5" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate03_group1polySurface23_6" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate03_group1polySurface17_7" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate03_group1polySurface18_8" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate03_group1polySurface20_9" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate03_group1polySurface16_10" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate03_group1FBXASC229FBXASC156FBXASC134F_f6669f6_11" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate03_group1FBXASC229FBXASC156FBXASC134F_f20052c_12" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate04_group3group2polySurface40_13" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate04_polySurface10_mate04_group5_14" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface23_15" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface24_16" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface21_17" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface18_18" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface3_19" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface4_20" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface6_21" position={[-0.009, -0.021, -0.056]} scale={0.025}>
            <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface5_22" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface19_23" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface7_24" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface9_25" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface8_26" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface25_27" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface15_28" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface16_29" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface13_30" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface26_31" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface17_32" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface20_33" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface22_34" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface14_35" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_group5_mate04_polySurface29_36" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material} />
          </group>
          <group name="group1_group2_mate04_polySurface1_37" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_1} />
          </group>
          <group name="group1_group2_mate04_polySurface2_38" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material_1} />
          </group>
          <group name="polySurface2_mate04_group3group2polySurface40_group1_group2_42" position={[-0.009, -0.021, -0.051]} scale={0.025}>
            <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.material} />
          </group>
        </group>
        <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material_1} position={[0.009, -0.021, 0.049]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.025} />
        <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.material} position={[0.009, -0.021, 0.049]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/huawei-transformed.glb')
