/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 iphone.gltf --transform 
Files: iphone.gltf [973.89KB] > iphone-transformed.glb [1.32MB] (-35%)
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-iphone-13-pro-2021-a35156d91cf44e70a2fdfeade54ae0b2
Title: (FREE) iPhone 13 Pro 2021
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/iphone-transformed.glb')
  return (
    <group {...props} dispose={null}  rotation={[0, Math.PI / 2, 0]}> {/* Add rotation here */}
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[-0.057, 0.789, -0.14]} scale={0.024} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial002} position={[-0.057, 0.789, -0.14]} scale={0.024} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial003} position={[-0.057, 0.789, -0.14]} scale={0.024} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material} position={[-0.057, 0.789, -0.14]} scale={0.024} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Display} position={[-0.057, 0.789, -0.14]} scale={0.024} />
    </group>
  )
}

useGLTF.preload('/iphone-transformed.glb')
